apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-data" (include "cpp-ci.fullname" .) }}
  labels:
    {{- include "cpp-ci.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.data.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   
  storageClassName: ""
  local:
    path: {{ .Values.storage.data.pathOnNode }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeName }}