apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cpp-ci.fullname" . }}
  labels:
    {{- include "cpp-ci.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cpp-ci.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cpp-ci.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cpp-ci.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: {{ .Values.service.ssh.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mnt
              mountPath: /mnt
              readOnly: false
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    if [ ! -d /mnt/conan2 ]; then
                      echo 'Profile not found, detecting...'
                      mkdir /mnt/conan2
                      conan profile detect --force
                      chown -R {{ .Values.sshUser }}:{{ .Values.sshUser }} /mnt/conan2
                    else
                      echo 'Profile already exists, skipping detect to preserve customizations'
                    fi
      volumes:
        - name: mnt
          persistentVolumeClaim:
            claimName: {{ printf "%s-mnt" (include "cpp-ci.fullname" .) }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
