apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ssh" (include "cpp-ci.fullname" .) }}
  labels:
    {{- include "cpp-ci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ssh.type }}
  ports:
    - port: {{ .Values.service.ssh.port }}
      targetPort: ssh
      {{- if eq .Values.service.ssh.type "NodePort" }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "cpp-ci.selectorLabels" . | nindent 4 }}
